// Mocks generated by Mockito 5.3.2 from annotations
// in pokedex/test/controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter/material.dart' as _i8;
import 'package:infinite_scroll_pagination/infinite_scroll_pagination.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pokedex/bloc/poke_controller.dart' as _i4;
import 'package:pokedex/database/local_storage.dart' as _i3;
import 'package:pokedex/entities/pokemon.dart' as _i5;
import 'package:pokedex/services/dio_pokemon.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokeDio_0 extends _i1.SmartFake implements _i2.PokeDio {
  _FakePokeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocalDex_1 extends _i1.SmartFake implements _i3.LocalDex {
  _FakeLocalDex_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PokeController].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokeController extends _i1.Mock implements _i4.PokeController {
  @override
  _i2.PokeDio get pokeDio => (super.noSuchMethod(
        Invocation.getter(#pokeDio),
        returnValue: _FakePokeDio_0(
          this,
          Invocation.getter(#pokeDio),
        ),
        returnValueForMissingStub: _FakePokeDio_0(
          this,
          Invocation.getter(#pokeDio),
        ),
      ) as _i2.PokeDio);
  @override
  _i3.LocalDex get localDex => (super.noSuchMethod(
        Invocation.getter(#localDex),
        returnValue: _FakeLocalDex_1(
          this,
          Invocation.getter(#localDex),
        ),
        returnValueForMissingStub: _FakeLocalDex_1(
          this,
          Invocation.getter(#localDex),
        ),
      ) as _i3.LocalDex);
  @override
  List<_i5.Pokemon> get pokeList => (super.noSuchMethod(
        Invocation.getter(#pokeList),
        returnValue: <_i5.Pokemon>[],
        returnValueForMissingStub: <_i5.Pokemon>[],
      ) as List<_i5.Pokemon>);
  @override
  set pokeList(List<_i5.Pokemon>? _pokeList) => super.noSuchMethod(
        Invocation.setter(
          #pokeList,
          _pokeList,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i6.Stream<_i4.StatePage> get streamFilterState => (super.noSuchMethod(
        Invocation.getter(#streamFilterState),
        returnValue: _i6.Stream<_i4.StatePage>.empty(),
        returnValueForMissingStub: _i6.Stream<_i4.StatePage>.empty(),
      ) as _i6.Stream<_i4.StatePage>);
  @override
  _i6.Stream<_i7.PagingState<int, _i5.Pokemon>> get streamPagingState =>
      (super.noSuchMethod(
        Invocation.getter(#streamPagingState),
        returnValue: _i6.Stream<_i7.PagingState<int, _i5.Pokemon>>.empty(),
        returnValueForMissingStub:
            _i6.Stream<_i7.PagingState<int, _i5.Pokemon>>.empty(),
      ) as _i6.Stream<_i7.PagingState<int, _i5.Pokemon>>);
  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i6.Future<List<_i5.Pokemon>> getPokemon(int? index) => (super.noSuchMethod(
        Invocation.method(
          #getPokemon,
          [index],
        ),
        returnValue: _i6.Future<List<_i5.Pokemon>>.value(<_i5.Pokemon>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i5.Pokemon>>.value(<_i5.Pokemon>[]),
      ) as _i6.Future<List<_i5.Pokemon>>);
  @override
  _i6.Future<List<_i5.Pokemon>> search(
    String? value, {
    List<_i5.Pokemon>? list = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [value],
          {#list: list},
        ),
        returnValue: _i6.Future<List<_i5.Pokemon>>.value(<_i5.Pokemon>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i5.Pokemon>>.value(<_i5.Pokemon>[]),
      ) as _i6.Future<List<_i5.Pokemon>>);
  @override
  _i6.Future<List<_i5.Pokemon>> favorites(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #favorites,
          [value],
        ),
        returnValue: _i6.Future<List<_i5.Pokemon>>.value(<_i5.Pokemon>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i5.Pokemon>>.value(<_i5.Pokemon>[]),
      ) as _i6.Future<List<_i5.Pokemon>>);
  @override
  _i6.Future<List<_i5.Pokemon>> sort(String? value) => (super.noSuchMethod(
        Invocation.method(
          #sort,
          [value],
        ),
        returnValue: _i6.Future<List<_i5.Pokemon>>.value(<_i5.Pokemon>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i5.Pokemon>>.value(<_i5.Pokemon>[]),
      ) as _i6.Future<List<_i5.Pokemon>>);
  @override
  _i6.Future<List<_i5.Pokemon>> getGeneration(String? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGeneration,
          [value],
        ),
        returnValue: _i6.Future<List<_i5.Pokemon>>.value(<_i5.Pokemon>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i5.Pokemon>>.value(<_i5.Pokemon>[]),
      ) as _i6.Future<List<_i5.Pokemon>>);
  @override
  _i6.Future<List<_i5.Pokemon>> searchByName(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByName,
          [name],
        ),
        returnValue: _i6.Future<List<_i5.Pokemon>>.value(<_i5.Pokemon>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i5.Pokemon>>.value(<_i5.Pokemon>[]),
      ) as _i6.Future<List<_i5.Pokemon>>);
  @override
  _i6.Future<List<_i5.Pokemon>> setFilter({
    required List<String>? types,
    required List<String>? heights,
    required List<String>? weights,
    required _i8.RangeValues? range,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFilter,
          [],
          {
            #types: types,
            #heights: heights,
            #weights: weights,
            #range: range,
          },
        ),
        returnValue: _i6.Future<List<_i5.Pokemon>>.value(<_i5.Pokemon>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i5.Pokemon>>.value(<_i5.Pokemon>[]),
      ) as _i6.Future<List<_i5.Pokemon>>);
}

/// A class which mocks [LocalDex].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDex extends _i1.Mock implements _i3.LocalDex {
  @override
  List<_i5.Pokemon> get myList => (super.noSuchMethod(
        Invocation.getter(#myList),
        returnValue: <_i5.Pokemon>[],
        returnValueForMissingStub: <_i5.Pokemon>[],
      ) as List<_i5.Pokemon>);
  @override
  set myList(List<_i5.Pokemon>? _myList) => super.noSuchMethod(
        Invocation.setter(
          #myList,
          _myList,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i6.Future<List<_i5.Pokemon>> getPokemons(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getPokemons,
          [key],
        ),
        returnValue: _i6.Future<List<_i5.Pokemon>>.value(<_i5.Pokemon>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i5.Pokemon>>.value(<_i5.Pokemon>[]),
      ) as _i6.Future<List<_i5.Pokemon>>);
  @override
  _i6.Future<dynamic> addList(List<_i5.Pokemon>? poke) => (super.noSuchMethod(
        Invocation.method(
          #addList,
          [poke],
        ),
        returnValue: _i6.Future<dynamic>.value(),
        returnValueForMissingStub: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);
  @override
  _i6.Future<dynamic> addPokemon(
    _i5.Pokemon? poke,
    String? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPokemon,
          [
            poke,
            key,
          ],
        ),
        returnValue: _i6.Future<dynamic>.value(),
        returnValueForMissingStub: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);
  @override
  _i6.Future<dynamic> removePokemon(
    _i5.Pokemon? poke,
    String? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removePokemon,
          [
            poke,
            key,
          ],
        ),
        returnValue: _i6.Future<dynamic>.value(),
        returnValueForMissingStub: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);
}
